---
- name: Hardened Ubuntu 24.04 Setup for Hetzner
  hosts: all
  become: true
  become_method: sudo
  vars:
    username: user

  roles:
    - role: common
      tags: [common]

    - role: docker
      tags: [docker]

    - role: security
      tags: [security]

    - role: immich
      tags: [immich]
      vars:
        storagebox_url: "{{ vault_storagebox_url | default('') }}"
        storagebox_user: "{{ vault_storagebox_user | default('') }}"
        storagebox_password: "{{ vault_storagebox_password | default('') }}"
        postgres_password: "{{ vault_postgres_password | default('postgres') }}"
